services:
  template-search-mcp:
    image: comol/template-search-mcp:latest
    container_name: template-search-mcp
    ports:
      - "8004:8004"
    environment:
      - USESSE=true
      - RESET_DATABASE=false
      - RESET_CACHE=false
#      - OPENAI_API_BASE= # расскомментируйте и задайте, если требуется использование OpenAI-совместимого API, а также укажите токен в .env файле
#      - OPENAI_MODEL=    # расскомментируйте и задайте, если требуется использование OpenAI-совместимого API
#      - EMBEDDING_MODEL= 
    env_file: .env
    volumes:
      - ./templates:/app/data
      - ./chroma_db:/app/chroma_db
#      - ./model_cache:/app/model_cache # расскомментируйте, если используется кастомная EMBEDDING_MODEL
    restart: unless-stopped
